### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by mhofman** [ungap/weakrefs#1] opened 2019-09-27 19:28 UTC
Maybe there's something I'm missing about IE11, but WeakMap hold their keys weakly. They're implemented using ephemerons not weak references.

The purpose of WeakRef and FinalizationGroup is to hold values/target weakly. As such a spec complicant WeakMap cannot be used to implement the Weakrefs proposal.

In the Spidermonkey shell my [shim](https://github.com/mhofman/tc39-weakrefs-shim) uses WeakMap combined with their non-standard [nondeterministicGetWeakMapKeys](https://github.com/mhofman/tc39-weakrefs-shim/blob/spec-update/src/spidermonkey/internal.ts#L42).

If there are other ways to expose the collection behavior is some browsers, I'd be happy to add implementations for them in my shim.

**Comment by WebReflection** [comment] 2019-09-27 20:21
sorry, I'm having hard time understanding your issue. IE11 supports WeakMap natively, but also I don't understand what you are asking. Do you mind to elaborate a bit more, tell me with an example what's not working as intended, or simply file a PR?
Thank you!

**Comment by mhofman** [comment] 2019-09-27 20:37
WeakMap and WeakRef are orthogonal features and one cannot be implemented using the other.

The following is the expected behavior, assuming the engine can perform garbage collection:
```javascript
let wr = new WeakRef({});
// Turn the event-loop since according to spec, 
// WeakRef must hold the target strongly for the current synchronous execution
await new Promise(resolve => setTimeout(resolve, 0));
gc();
assert(wr.deref() === undefined)
```

and
```javascript
let fg = new FinalizationGroup((holdings => console.log(...holdings));
let target = {};
fg.register(target, 'should not print');
gc();
fg.cleanupSome(); // No console output
```

Based on my reading of your implementation and your tests, `wr.deref()` always returns the target since the WeakMap key is the WeakRef instance. The target's lifetime will always be at least as long as the weakref's.

FinalizationGroup seems to take no regard to the target object's lifetime and always includes all current holdings in the cleanup callback.

**Comment by WebReflection** [comment] 2019-09-27 20:41
you used `gc()` in your code, which is unfortunately (or fortunately) not exposed to the browser.

there are things that cannot be polyfilled 1:1 with specs, as these are new, and `WeakMap` itself is one of these things.

accordingly, do you have any suggestion on how to improve this poly, or you are suggesting I should point to your code in the README ?

**Comment by WebReflection** [comment] 2019-09-27 20:43
also worth mentioning the philosophy behind this project:
https://ungap.github.io/#pragmaticisbetterthansubsupimsupsubperfect

**Comment by mhofman** [comment] 2019-09-27 20:49
Correct, testing of weakrefs requires `gc()` to be available. I simply use it to point out what the behavior of weakrefs is when a collection occurs.

What I'm saying is that unless the JS environement exposes some kind of collector observation primitive, it's impossible to implement weakrefs in JavaScript.

If you want to implement the API surface without implementing the collection behavior, then `WeakRef` is fine, but `FinalizationGroup` needs to be fixed (the cleanup callback can never be invoked since you cannot detect when an object has been collected).

I personally do not believe this API should be provided if the finalization cannot be exposed, and the developer should instead test if the feature is available.

**Comment by mhofman** [comment] 2019-09-27 20:53
There should at least be a disclaimer that this implementation does not allow detection of when an object has been collected and that `WeakRef` effectively keeps a strong reference to the target.

**Comment by WebReflection** [comment] 2019-09-27 20:58
> There should at least be a disclaimer that this implementation does not allow detection of when an object has been collected

'cause that's not possible for any polyfill, so it's kinda implicit?

> WeakRef effectively keeps a strong reference to the target

do you think there's a way to improve that, in this code?

**Comment by mhofman** [comment] 2019-09-27 21:11
> > There should at least be a disclaimer that this implementation does not allow detection of when an object has been collected
> 
> 'cause that's not possible for any polyfill, so it's kinda implicit?

It is possible in node with a native addon.

> 
> > WeakRef effectively keeps a strong reference to the target
> 
> do you think there's a way to improve that, in this code?

No, again it's not possible unless there's some kind of environment API that can be (ab)used.

Besides the wrong implementation for FinalizationGroup, my concern is that the Readme implies that this polyfill is a half working solution thanks to WeakMap and that finalization can be detected through polling `cleanupSome`. Using WeakMap doesn't help in any way implementing this feature. And since finalization is not observable, `cleanupSome` should not do anything.

**Comment by WebReflection** [comment] 2019-09-28 10:10
Once again, this is [the philosophy of this project](https://ungap.github.io/#pragmaticisbetterthansubsupimsupsubperfect):

> **⚠ Pragmatic is better than (im)perfect**
>
> There are parts of the specifications that are very hard, if not impossible, to polyfill. The main purpose of this project is to help developers move forward, and possibly without unnecessary bloat. This basically means that polyfills are written to support 99% of the use cases, without granting 100% spec compliance.

The readme also qualifies the poly as _sham_. The advantage of polyfills is that these become useless once the browser implements things properly.

In a world where every WeakMap polyfill implementation is broken in a way or another, I don't care if this one is imperfect, as long as it works.

The `this` is not strongly held anywhere, so the WeakMap works as meant per "best effort" implementation.

Accordingly, there's nothing to do here, beside maybe underlying in the README this poly is not perfect.

If you have any hint, I'll update that, but I'm closing this for now, as it already landed and it can be already handy.

Regards.

**Closed as completed by WebReflection** 2019-09-28 10:10 UTC

**Comment by mhofman** [comment] 2019-10-01 23:57
I understand providing a sham that partially implements what it can, but in the case of both `FinalizationGroup.cleanupSome` and `WeakRef`, the implementation here goes against the intent of the API proposal.

Developers use `cleanupSome` to cleanup resources associated to objects that have been collected.
As such, cleanupSome's iterator should only yield holdings associated to target objects that have been collected. If you cannot observe collection, cleanupSome should not return anything. If you do return holdings for still alive objects, the developer using your sham will end up cleanup resources that are still in use.

Similarly, the intent of the WeakRef API is to allow the developer to not hold an object strongly. It is one thing for a JS engine to not collect objects, and another thing for a userland library to leak objects in a collecting environment.

On Medium you mentioned regarding your WeakMap polyfill:
> I’ve published a library that was simply leaking all objects forever. As of today, that’s probably my most epic-fail approach to a polyfill

With this WeakRef sham you are basically re-doing the same thing.

I see 3 approaches:
- Make clear that this sham cannot observe collection and thus a `WeakRef` is actually a strong reference to the target (leaks). Also change the cleanupSome implementation to do nothing.
- Provide some kind of mock garbage collection interface where the developer informs the sham that certain objects are no longer in use. The sham can then internally clear the related `WeakRef` objects and trigger the cleanup callbacks. I actually wrote a prototype some time ago that does a more complex version of this.
- Not provide this sham at all and have developers feature test for this and do progressive enhancement.

**Comment by mindplay-dk** [comment] 2021-03-21 11:55
From the explanation in the README, I gathered the "sham" part was explicitly about needing to manually triggering the `cleanupSome` function of `FinalizationGroup`.

> ![image](https://user-images.githubusercontent.com/103348/111903107-de79db00-8a40-11eb-9165-c0ff5b1c88b9.png)

Looking at the actual source-code, I thought, huh, that's brilliant!

```
    var wr = new WeakMap;
    function WeakRef(value) {
      wr.set(this, value);
    }
```

You're using the `WeakMap` instance itself as the key in a `WeakMap`, where the actual values are kept.

I would have thought that would work. In fact, I have no idea why it doesn't. I don't have a very deep understanding of how garbage collection or `WeakMap` works internally - just that "weak maps let me keep things in a map without blocking the garbage collector", which is probably where the average JS developers' understanding of this subject ends, right?

I actually expected this to work.

I finally tossed up a [fiddle](https://jsfiddle.net/t9h6eLgu/) to see for myself:

![WeakRef](https://user-images.githubusercontent.com/103348/111903258-a7f09000-8a41-11eb-8517-f5ba10525b98.gif)

In deed, this approach does not seem to work.

I still have no idea why.

What I'm not understanding at this moment, is why create a polyfill for something that cannot be polyfilled? 

I'm also not understanding why this uses `WeakMap` in the first place? That just adds to the confusion for anyone reading the source-code. I was certain this did *something* related to memory management - but it seems the following does exactly the same thing:

```js
function WeakRef(value) {
  this.value = value;
}

Object.defineProperties(
  WeakRef.prototype,
  {
    deref: {
      value: function deref() {
        return this.value;
      }
    }
  }
);
```

At least, this way, it's clear that this has nothing to do with memory management - without understanding anything about garbage collection or `WeakMap`, I can understand why this *doesn't* work. 

(Also, this would work in every browser since the dawn of time, if that matters.)

The only motivation for using a `WeakRef` in the first place, is for memory management effects - which you do not get with this polyfill. So this is confusingly *not* an implementation of weak references.

I have to agree with @mhofman that there is no use-case where using this is appropriate.

I think there should be an unambiguous ⚠ **WARNING** ⚠ in the README, stating that this is exclusively about getting code to *run*, if you absolutely must - but that this *will* leak memory anywhere it's being used with the intention of achieving memory management effects, e.g. **everywhere**.

Linking to this issue would probably be a good idea as well.

**Comment by WebReflection** [comment] 2021-03-21 12:20
I'd say don't use this polyfill, as it's not a polyfill, because WeakRef cannot be polyfilled.

There's nothing else I can do ... either you find a way to make WeakRef polyfillable and you file a PR, or I'll close this issue and its comment as there's nothing I can do, and I am not enforcing you to use this polyfill, I can as well publish it and use it only for myself, as long as its constraints are clear, which is what the README tries to explain.

Have a nice Sunday 👋
